<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Travigo - Travel for everyone</title>
	<link rel="stylesheet" type="text/css" href="/css/style.css">
	<link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Paytone+One&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
	<meta name="description" content="Try the best travel experience with travigo travel">
	<meta name="keywords" content="trave, Paris, London, Cairo, plan, plane ticket">

</head>
<body>
	<!--header--->
	<header>
		<a href="index.html" >
			<img src="/img/white-logo.png" alt="Travigo Travel logo" id="white-logo">
			<img src="/img/blue-logo.png" alt="Travigo Travel logo" id="blue-logo" class="hide">
		</a>
		<div class="bx bx-menu" id="menu-icon"></div>

		<ul class="navbar">
			<li><a href="/page/index/">Home</a></li>
			<li><a href="/page/travels/">Tours</a></li>
			<li><a href="/page/about/">About</a></li>
			<li><a href="/page/Contact/">Contact Us</a></li>
		</ul>
	</header>