<?php include VIEW . 'Header.phtml'; ?>
<!--Home section--->
<section class="home" id="home">
		<div class="home-text">
			<h1>Travigo <br> Travel</h1>
			<p>Explore our trips and live The Good Life with Travigo <br> Tours that make you fall in love with the world.</p>
			<a href="tours.html" class="home-btn">Let's go now</a>
		</div>
	</section>

	<!--container--->
	<section class="container">

		<div class="row-items">
			<div class="container">
				
				<div class="title">
					<h2>Who are we</h2>
				</div>
				<br>
				<p>Founded in 2005 by three university friends in Düsseldorf (Germany), trivago has since become a leading global accommodation search website. We are focused on reshaping the way millions of travelers search for and compare hotels and other accommodations. Part of Expedia Group (NASDAQ: TRVG), trivago’s mission is to become your companion to experience our world. </p>
			</div>
			<div class="container-img-b">
				<img src="/img/tourism.jpg">
			</div>

		</div>
	</section>

	<!--container--->
	<section class="container">
		<div class="row-items">
			<div class="container-img-b">
				<img src="/img/maroc.jpg">
			</div>
			<div class="container-box">
				<p>we organize perfect trips all over Morocco.
					We want you to enjoy and be moved by your experience here, whether it’s your first time, or a return trip.
					
					We want you to see our beautiful country in the way you want to.
					
					We will design a trip that suits the way you travel, and what you value.
					
					Do you want Luxury? Adventure? Simplicity? There are so many ways to focus your time here, let’s choose the right things for you.
					
					Throughout, OmegaTours takes care of everything, from the day you land, until the moment we say goodbye at the airport.
					
					We handle all the logistics: in-country travel planning; book accommodations; and provide comfortable, private transportation.
					
					But the most important thing is our people: Omega’s knowledgeable, friendly guides and drivers know and love this land, and love to share it with visitors.
					
					We also have a wonderful network of people to host and help you go deeper in what you care to see: the freedom to explore in balance with your safety.
					Come and see Morocco with us! You won’t be disappointed. </p>
			</div>
			

		</div>
	</section>

	<!--destination section--->
	<section class="destination" id="destination">
		<div class="title">
			<h2>Find out more</h2>
		</div>

		<div class="destination-content">
			<div class="blog-content">
				<img src="/img/img-1.jpg">
				<h5>Careers at trivago</h5>
				<p>Find out more about our open roles, working culture, benefits, D&I approach and how we recruit.</p>
			</div>

			<div class="blog-content">
				<img src="/img/img-2.jpg">
				<h5>Tech blog</h5>
				<p>Get insight into our projects, prototypes and tech stack from our developers!</p>
			</div>

			<div class="blog-content">
				<img src="/img/img-3.jpg">
				<h5>trivago blog</h5>
				<p>A central source of actionable insights into hotel marketing, technology, and trends.</p>
			</div>

		</div>
	</section>
<?php include VIEW . 'Footer.phtml'; ?>