<?php include VIEW . 'Header.phtml'; ?>
<!--Home section--->
<section class="home" id="home">
		<div class="home-text">
			<h1>Travigo <br> Travel</h1>
			<p>Explore our trips and live The Good Life with Travigo <br> Tours that make you fall in love with the world.</p>
            <a href="tours.html" class="home-btn">Let's go now</a>
		</div>
    </section>
    <div>
        <h2 class="section-f-header">Contact Us</h2>
    </div>
    <section>
		<div class="contact-section">
			<form class="contact-form">
				<div class="names">
					<div class="first-name" >
						<label>FIRST NAME</label>
						<input type="text" name="first name">
					</div>
					<div class="last-name">
						<label>LAST NAME</label>
						<input type="text" name="last name">
					</div>
				</div>
				
				<div class="email">
					<label>EMAIL</label>
					<input type="email" name="email">
				</div>
				<div class="message" >
					<label>MESSAGE</label>
					<textarea name="message"  cols="30" rows="10"></textarea>
				</div>
				<div class="send-message">
					<button type="submit">Send Message</button>
				</div>
			</form>
			<div>
				<img src="/img/contact-us-[Converted] 1.png" alt="contact image">
			</div>
		</div>
	</section>
<?php include VIEW . 'Footer.phtml'; ?>