<?php include VIEW . 'Header.phtml'; ?>
<!--Home section--->
<section class="home" id="home">
		<div class="home-text">
			<h1>Travigo <br> Travel</h1>
			<p>Explore our trips and live The Good Life with Travigo <br> Tours that make you fall in love with the world.</p>
			<a href="tours.html" class="home-btn">Let's go now</a>
		</div>
	</section>

	<!--container--->
	<section class="container">
		<div class="text">
			<h2>Start Your Vacation <br> with Lots of Services!</h2>
		</div>

		<div class="row-items">
			<div class="container-box">
				<div class="container-img">
					<img src="/img//trip1.png">
				</div>
				<h4>Ship Cruises</h4>
				<p>150 Properties</p>
			</div>

			<div class="container-box">
				<div class="container-img">
					<img src="/img//trip2.png">
				</div>
				<h4>Food Tours</h4>
				<p>150 Properties</p>
			</div>

			<div class="container-box">
				<div class="container-img">
					<img src="/img//trip3.png">
				</div>
				<h4>Summer Rest</h4>
				<p>150 Properties</p>
			</div>

		</div>
	</section>

	<!--Package section--->
	<section class="package" id="package">
		<div class="title">
			<h2>Our Upcoming <br> Tour Package</h2>
		</div>

		<div class="package-content">
			<div class="box">
				<div class="thum">
					<img src="/img/img1.png">
					
				</div>

				<div class="dest-content">
					<div class="location">
						<h4>London</h4>
						<p>4h - 5h</p>
					</div>
					<div class="stars">
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
					</div>
				</div>
			</div>

			<div class="box">
				<div class="thum">
					<img src="/img//img2.png">
					
				</div>

				<div class="dest-content">
					<div class="location">
						<h4>New York</h4>
						<p>4h - 5h</p>
					</div>
					<div class="stars">
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
					</div>
				</div>
			</div>

			<div class="box">
				<div class="thum">
					<img src="/img//img3.png">
					
				</div>

				<div class="dest-content">
					<div class="location">
						<h4>Dubai</h4>
						<p>4h - 5h</p>
					</div>
					<div class="stars">
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
					</div>
				</div>
			</div>

		</div>
	</section>

	<!--destination section--->
	<section class="destination" id="destination">
		<div class="title">
			<h2>Our Most Popular <br> Destination!</h2>
		</div>

		<div class="destination-content">
			<div class="col-content">
				<img src="/img//img-1.jpg">
				<h5>Machu Picchu</h5>
				<p>PERU</p>
			</div>

			<div class="col-content">
				<img src="/img//img-2.jpg">
				<h5>Machu Picchu</h5>
				<p>PERU</p>
			</div>

			<div class="col-content">
				<img src="/img//img-3.jpg">
				<h5>Machu Picchu</h5>
				<p>PERU</p>
			</div>

			<div class="col-content">
				<img src="/img//img-4.jpg">
				<h5>Machu Picchu</h5>
				<p>PERU</p>
			</div>

			<div class="col-content">
				<img src="/img//img-5.jpg">
				<h5>Machu Picchu</h5>
				<p>PERU</p>
			</div>

			<div class="col-content">
				<img src="/img//img-6.jpg">
				<h5>Machu Picchu</h5>
				<p>PERU</p>
			</div>

		</div>
	</section>
<?php include VIEW . 'Footer.phtml'; ?>