<?php include VIEW . 'Header.phtml'; ?>
<!--Home section--->
<section class="home" id="home">
		<div class="home-text">
			<h1>Travigo <br> Travel</h1>
			<p>Explore our trips and live The Good Life with Travigo <br> Tours that make you fall in love with the world.</p>
		</div>
	</section>

    <!--tours-->
    <section class="package" id="package">
		<h2 class="section-f-header">Tours</h2>
		<div class="package-content">
		<?php if (array_key_exists('travels', $this->viewData))
	        foreach($this->viewData['travels'] as $travel) { ?>
			<div class="box">
				<div class="thum">
					<img src="/img/<?php echo $travel['image']; ?>">
					 
				</div>

				<div class="dest-content">
					<div class="location">
						<h4><?php echo $travel['destination'] ?></h4>
						<p>4h - 5h</p>
					</div>
					<div class="stars">
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
						<a href="#"><i class='bx bxs-star'></i></a>
					</div>
				</div>
			</div>
			<?php } ?>
		</div>
	</section>
<?php include VIEW . 'Footer.phtml'; ?>