<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create travel</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <form action="http://travigo.com/Admin/Create/add" method="POST" enctype="multipart/form-data" class="mx-auto" style="width:400px;">
            <h1>add new destination</h1>
            <div class="mb-3">
                <label class="form-label">destination</label>
                <input type="text" name="destination" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
            <label  class="form-label">choose the picture of your destination</label>
                <input type="file" name="image" class="form-control" id="exampleInputPassword1">
            </div>
            <button type="submit" name="submit" class="btn btn-primary">Add Your new Destination</button> <br> <br>
            <a class="btn btn-danger" href="http://localhost/5th%20BRIEF/public/Admin/Dashboard">back to dashboard</a>
        </form>
    </div>

</body>

</html>